name: Publish the built software

on:
  push:
    tags:
      - '*'

jobs:
  build-and-upload:
    name: Package software on three platforms and upload

    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19

      - name: Go Mod
        run: go mod tidy

      - name: Build
        run: go build . && ls

      - name: Generate the artifacts
        uses: skx/github-action-build@master

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          args: 'gin-api*'
